config/routes.rb
NewCodelearn::Application.routes.draw do
  
  devise_for :users
    root "concept_lessons#index", as: "android_tutorial"
  get "/:app_name/:token(/:done)" => "app_lessons#lesson_with_token", as: "app_tutorial_lesson_with_token", :constraints => {:app_name => /twitter/}
  get "/:template" => "concept_lessons#view", as: "android_concept_lesson"
  

  

end

app/models/app_lesson.rb
class AppLesson < ActiveRecord::Base
	has_many :progresses, foreign_key: :lesson_number, primary_key: :number
end

app/models/current_user_lesson.rb
class CurrentUserLesson < ActiveRecord::Base
end

app/models/progress.rb
class Progress < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :progresses

end

app/controllers/app_lessons_controller.rb
class AppLessonsController < ApplicationController
  layout "syndicate"

  before_filter :authenticate_user!, except: [:incoming, :landing_page]

  def lesson_with_token
	 @app_name = params[:app_name]
	 @lessons = AppLesson.includes(:progresses)
	 @current_lesson = AppLesson.find_by_token(params[:token])
	 @next_lesson = AppLesson.find_by_number(@current_lesson.number + 1)
	 current_user_lesson_entry = CurrentUserLesson.find_by_user_id_and_lesson_number(current_user.id,@current_lesson.number) 

	 if params[:done] and !current_user_lesson_entry.nil? and current_user_lesson_entry.completed == true
		 @done = true
	 else
		 user_lesson = CurrentUserLesson.find_or_create_by_user_id(current_user.id)
		 user_lesson.lesson_number = @current_lesson.number
		 user_lesson.completed = false
		 user_lesson.save
		 @done = false
	 end

	 @progress_percent = Progress.where( user_id: current_user.id).length * 100 / AppLesson.all.length
		
	 render :lesson and return
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concept_lessons_controller.rb
class ConceptLessonsController < ApplicationController
  layout "syndicate"

  def index
  end

  def view
	  @template = "concept_lessons/#{params[:template].gsub('-','_')}"


	  case params[:template]
	  when "android-introduction"
		  @description = "Wondering what is Android development ? Check this lesson to know about Activity, View, Intent, Service, Broadcast Receivers, Notification and sqlite database in Android."
		  @title = "What is Android ? All you need to know for learning Android Development"
		  @keyword = "Android, Introduction, Beginner, Sqlite, Database, Activity, View, Intent, Service, Broadcast, Receivers"
		  @disqus_identifier = "concept-lesson-1"
	  when "android-setup"
		  @description = "Learn how to setup Android SDK after you download on your PC. It includes screencast for setting up the Android development kit and steps to setup USB Debugging tools in Android."
		  @title="Android Development Environment Setup"
		  @disqus_identifier = "concept-lesson-2"
	  when "android-hello-world"
		  @description = "Android Hello World chapter describes steps to create your first Android App. You also get to learn about various tools used in Android App Development. "
		  @title = "Android Hello World - Steps to build a simple Hello world App"
		  @disqus_identifier = "concept-lesson-3"
	  when "android-layout"
		  @description = "This Android Layout Tutorial describes layouts and its type such as grid layout, table layout,linear/relative android layout etc."
		  @title = "Android Layout"
		  @disqus_identifier = "concept-lesson-4"
	  when "android-activity"
		  @description = "This lesson covers Android activity and it's lifecycle. Learn Android activity concept through an example Android App."
		  @title = "Android Activity Lifecycle with Example"
		  @disqus_identifier = "concept-lesson-5"
	  when "android-intent"
		  @description = "Android Intent lets you navigate from one android activity to another. With examples, this tutorial also talks about various types of Android intents."
		  @title = "Android Intent Tutorial with Example"
		  @disqus_identifier = "concept-lesson-6"
	  when "android-views"
		  @description = "This Android Views tutorial explains elements such as gridview, imageview, scrollview, and textView in Android with example. Other widgets such as radio button, EditText and Checkbox are also covered in detail with sample examples for each android views element."
		  @title = "Android View Elements - Gridview, Scrollview, Imageview, Textview, Checkbox"
		  @disqus_identifier = "concept-lesson-7"
	  when "android-listview"
		  @description = "Android listView tutorial with real App example. All Android ListView concepts such as basic listview with ArrayAdapter and a custom listview with BaseAdapter are covered in details."
		  @title = "Android ListView | Everything you need to know about Android listview"
		  @disqus_identifier = "concept-lesson-8"
		  @keyword = "android listview,listview android,listview,android horizontal listview,android listview example,listview android example,android listview adapter,android custom listview,custom listview android,android listview header,listview in android,list view,android adapter,ArrayAdapter,BaseAdapter"
	  when "android-log"
		  @description = "Android log is a very important tool to for android development. Split across Beginner, Intermediate and Advanced sections, this lesson covers details with code examples."
		  @title = "Android Intent Tutorial with Example"
		  @disqus_identifier = "concept-lesson-6"

	  end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concept_lessons_helper.rb
module ConceptLessonsHelper
end

app/views/concept_lessons/index.html.erb
<!--<div class="dummy-container" style="margin-top: 1px solid #BABAB; width:100%; background: url('/assets/android-app-banner-1.png') top left no-repeat; background-position: fixed; background-size: 100%"> -->


	<div class="container">
		<h1 class="ac" style="margin-top:40px;">World's first <span class="text-success">interactive Android tutorial</span> <sup class="text-error" style="top:-1.5em; font-size:0.5em">Private Beta</sup></h1>
		<h3 class="ac muted">build a <strong>real app</strong> | work in <strong>real environment</strong>| get assisted in the browser <sup class="text-error" style="top:-1.5em; font-size:0.5em; visibility:hidden">Private Beta</sup></h3>
		<hr/>
		<div class="hero-unit faq">
			<div>
				<div class="row-fluid">
					<div class="span6">
						<iframe width="500" height="400"  style="max-width:100%" class="img-polaroid" src="//www.youtube.com/embed/FiuWvFyyuak" frameborder="0" allowfullscreen></iframe>
					</div>
					<div class="span1"></div>
					<div class="span5" style="margin-top:50px;">
						<p>We combine the best of online & offline learning. Let our <span class="text-error"> Virtual Assistant</span> mentor you, while you work peacefully on your computer.</p>
						<br/>	
						<%= link_to app_tutorial_lesson_with_token_path("twitter",AppLesson.first.token), :class => "btn btn-large btn-danger btn-block" do %>
							<h4>Learn by building a Twitter App<br/><small style="font-size:small; color:inherit">(It's FREE for now)</small></h4>
						<% end %>
						<div class="ac">or <a href="#conceptlessonsec">check our concept lessons</a></div>
					</div>
				</div>
			</div>
		</div>

	</div><!-- container -->
	<!--</div> -->
<script>
	$("body").css({ "background": "url(\'<%= image_path('android-app-banner-1.png') %>\') top left no-repeat fixed", "background-size": "100%", "background-color": "white"})
</script>
<hr/>
<div class="container">
	<div class="row-fluid">
		<div class="span4">
			<h2 class="ac">What is this !</h2>
			<ul>
				<li>There are two set of tutorials - <span class="text-error">Concept Lessons</span> & <span class="text-error">App Tutorial</span></li>
				<li><a href="#conceptlessonsec">Concept Lessons</a> exhaustively cover one Android concept at a time. Each lesson has a sample app.</li>
				<li><a href="#tutsection">App Tutorial</a> teaches how to implement the Android concepts in a real app. Requires downloading & installing Codelearn Eclipse plugin.</li>
			</ul>
		</div>
		<div class="span4">
			<h2 class="ac">Target Audience</h2>
			<p>If you belong to one of the category below, you are the right audience.</p>
			<ul>
				<li><strong>Hackers</strong> : People who are impatient & do not care.</li>
				<li><strong>Java Developers</strong> : People with prior knowledge of Java.</li>
				<li><strong>Android Newbies</strong> : People having no/little knowledge of Android</li>
			</ul>
		</div>
		<div class="span4">
			<%= link_to app_tutorial_lesson_with_token_path("twitter",AppLesson.first.token), :class => "btn btn-large btn-danger btn-block vertical-align-me" do %>
				<h4>Get Started with App Tutorial<br/><small style="font-size:small; color:inherit">(It's FREE. No login required)</small></h4>
			<% end %>
		</div>
	</div>
</div>
<hr/>

<div class="container">
	<h2 class="ac">What people are saying about it.</h2>
	<hr/>
	<div class="row-fluid">
		<h4 class="ac"><a href="http://zuberot.info" target="_blank">Zuberot</a>, an experienced Android developer from Macedonia</h4>
		<br/>
		<div class="row-fluid">
			<div class="span6">
				<%= image_tag "testimonials/zuberot-profile.png" %>
			</div>
			<div class="span6">
				<%= image_tag "testimonials/zuberot-tweet.png" %>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<%= image_tag "testimonials/tweet-translation.png" %>
			</div>
		</div>
	</div>
	<hr/>
	<div class="row-fluid">
		<h4 class="ac"><a href="http://www.reddit.com/r/Android/comments/1uv512/a_strange_yet_interesting_way_to_learn_android/" target="_blank">/r/Android sub-reddit</a></h4>
		<br/>
		<%= image_tag "testimonials/reddit.png" %>
	</div>
	<hr/>
	<div class="ac">
		<%= link_to app_tutorial_lesson_with_token_path("twitter",AppLesson.first.token), :class => "btn btn-large btn-danger" do %>
			<h4>Get Started with App Tutorial<br/><small style="font-size:small; color:inherit">(It's FREE. No login required)</small></h4>
		<% end %>
	</div>
	<hr/>

</div>


<div class="container">
	<div class="hero-unit ac" id="conceptlessonsec">
		<h2>Android Concept Lessons</h2>
		<p>For the first timers, this section is the right place to get started. Each lesson is exhaustive & cover the topic in great depth with an example app. Once done, move over to the <a href="#tutsection">App Tutorials</a> to see the concepts in action.</p>
	</div>
	<ol class="thumbnails" style="margin-left: 50px;">
		<li class="span3">
		<h3><%= link_to "1. Android Introduction", android_concept_lesson_path("android-introduction") %></h3>
		<p>First time with Android ? Check this lesson to know the basic building blocks of Android application (also known as Android Components) namely Activity, View, Intent, Service, Broadcast Receiver & Notification.</p>
		</li>
		<li class="span3">	
		<h3  style="line-height:1.5em"><%= link_to "2. Android Setup/Installation", android_concept_lesson_path("android-setup") %></h3>
		<p>Check the lesson to know how to setup Android SDK on your PC. It includes screencast for setting up the SDK. The SDK installation has pre-requisites like installing JDK. It is all being covered in the lesson.</p>
		</li>
		<li class="span4">
		<h3><%= link_to "3. Android Hello World", android_concept_lesson_path("android-hello-world") %></h3>
		<p>Done with installing the Android SDK but clueless on how to get started ? This lesson tells you how to get started with a Hello World Android app. Creating your app for the first time can be daunting to newbies. Here, we explain  what various input fields stand for during the app creation process. We have also explained the folder structure and different tools like Console, Logcat & DDMS which you will be needing during Android app development. </p>
		</li>
		<li class="span4">
		<h3><%= link_to "4. Android Layout", android_concept_lesson_path("android-layout") %></h3>
		<p>One of the important components of Android apps are View elements which are contained in a Viewgroup, also known as Layout. The Layout files are XML files. The User Interface design of your app starts with the Layout file & arranging View elements inside it. Follow this Android tutorial to know how to get started with Layouts & what are the most popular Layout types available in Android.</p>
		<p>Each Layout type has a separate project that you can download, import in Eclipse & see the Layout in action.</p>
		</li>
		<li class="span6">
		<h3><%= link_to "5. Android Activity", android_concept_lesson_path("android-activity") %></h3>
		<p>While creating Hello World app, you would have noticed that 'New Project' wizard asks you for an Activity name. Activity is the component of Android that you should be aware of. An Android app consists of multiple Activities. At a time,since, you are looking at only one Activity of an application, all other Activites (of the current app & the other apps) go to background. This is an Activity state. An Activity has many states & lifecycle, which you need to handle as an Android developer. Follow this Android Tutorial to dig deeper into an Activity, its state & lifecycle.</p>				
		<p>We have bundled an Android project <a href="https://github.com/pranayairan/Code-Learn-Android-Example/tree/master/CodeLearnActivityLifeCycle">CodelearnActivityLifeCycle</a> that will show you various Activity Lifecycle methods that gets triggered. Instructions on how to get the Activity to enter a particular lifecycle method is included in the lesson.</p>
		</li>
		
		<li class="span4">
		<h3><%= link_to "6. Android Intent", android_concept_lesson_path("android-intent") %></h3>
		<p>Done creating Activity & corresponding User Interface through Layout XML files ? It is time to learn how to navigate from one Activity to another. Intents in Android does exactly that. But there is more to it. You can pass data from one Activity to another. You can launch non-Activity components like Services, Notifications & even other Android apps.</p>
		<p>Checkout the bundled sample app <a href="https://github.com/pranayairan/Code-Learn-Android-Example/tree/master/CodeLearnHelloIntents">CodelearnHelloIntents</a> which shows all the above examples in action.</p>
		</li>
		<li class="span6">
		<h3><%= link_to "7. Android Views", android_concept_lesson_path("android-views") %></h3>
		<p>Earlier in Lesson 4, we introduced Android Layouts which contained various Android View elements. This Android tutorial introduces some of the standard View elements like Button, TextView, EditText, Radiobutton & Checkbox. It also talks about the View specific attributes that you can either set in the XML view file or set it through your Activity java code. Some views have Listeners to which you can attach your java code that gets activated on events. Example - a Button View getting clicked. The Listeners vary from element to element & have been covered in the specific elements.</p> 
		<p>After the standard/simple Views, some complex View elements like ImageView, ListView (just an introduction), GridView & ScrollView are also introduced with their specific attributes.</p>
		<p>We have included relevant code snippets but unfortunately did not get enough time to create sample projects for the same. If you are interested to contribute, do write to us.</p>
		</li>
		
		<li class="span4">
		<h3><%= link_to "8. Android ListView", android_concept_lesson_path("android-listview") %></h3>
		<p>Android ListView is one of the most ubiquitious but also one of the most difficult concept to understand. For the beginners, any list that you have seen on your Android phone (example list of phone numbers when you launch your contact) is implemented using Android ListView. Here we have tried making it as easier as possible for you by explaining the easiest way of implementing a basic Listview & then explaining what each line of code represent. We then follow the similar process with more complex ListView implementations.</p>
		<p>You would probably not want to miss the <a href="https://github.com/pranayairan/Code-Learn-Android-Example/tree/master/CodeLearnListExample">CodeLearnListExample</a> app that we have bundled with the lesson. The app will let you see various ListView implementations in action with instructions.</p>
		</li>
		
		<li class="span3">
		<h3><%= link_to "9. Android Log", android_concept_lesson_path("android-log") %></h3>
		<p>Your favorite Java dump command 'System.out.println()' does not work in Android. Know how to use to use the Log class. An extensive Android tutorial on how to use LogCat to view & filter the log messages.</p>
		</li>
		<li class="span4">
		<h3><a href="#">10. Android Dialogs / Popups / Toasts</a></h3>
		<p>...coming soon..</p>
		</li>
		<li class="span3">
		<h3><a href="#">11. File Handling in Android</a></h3>
		<p>...coming soon..</p>
		</li>
		<li class="span4">
		<h3 style="line-height:1.5em"><a href="#">12. Android Shared Preferences (Persistence)</a></h3>
		<p>...coming soon..</p>
		</li>
	</ol>
	<style>
		ol.thumbnails h3 {
			text-align:center
		}
	</style>
	<hr/>
	<div class="ac">
		<%= link_to app_tutorial_lesson_with_token_path("twitter",AppLesson.first.token), :class => "btn btn-large btn-danger" do %>
			<h4>Get Started with App Tutorial<br/><small style="font-size:small; color:inherit">(It's FREE. No login required)</small></h4>
		<% end %>
	</div>
	<hr/>
</div>

app/views/concept_lessons/view.html.erb
<%= stylesheet_link_tag "docs" %>
<link href="http://getbootstrap.com/docs-assets/css/pygments-manni.css" rel="stylesheet">

<style>
	.page-header h2 {
		margin-left: 10px;
	}
</style>

<div class="container bs-docs-container">
	<div class="row">
		<div class="span3">
			<div role="complementary" class="bs-sidebar hidden-print affix-top" style="height:100%; overflow-y: auto">
				<ul class="nav bs-sidenav" style="background-color:#F6F6F6">
					<!-- to be filled 
					<li class="active"><a href="#history">History</a></li> -->
				</ul>
			</div>
		</div>
		<div role="main" class="span9">
			<!-- History
			==================================================
				<div class="page-header">
					<h1 id="history">History</h1>
				</div>
				<p class="lead">Originally created by a designer and a developer at Twitter, Bootstrap has become one of the most popular front-end frameworks and open source projects in the world.</p>
				<p>Bootstrap was created at Twitter in mid-2010 by <a href="https://twitter.com/mdo">@mdo</a> and <a href="https://twitter.com/fat">@fat</a>. Prior to being an open-sourced framework, Bootstrap was known as <em>Twitter Blueprint</em>. A few months into development, Twitter held its <a href="https://blog.twitter.com/2010/hack-week">first Hack Week</a> and the project exploded as developers of all skill levels jumped in without any external guidance. It served as the style guide for internal tools development at the company for over a year before its public release, and continues to do so today.</p>
				<p>Originally <a href="https://dev.twitter.com/blog/bootstrap-twitter">released</a> on <a href="https://twitter.com/mdo/statuses/104620039650557952"><time datetime="2011-08-19 11:25">Friday, August 19, 2011</time></a>, we've since had over <a href="https://github.com/twbs/bootstrap/releases">twenty releases</a>, including two major rewrites with v2 and v3. With Bootstrap 2, we added responsive functionality to the entire framework as an optional stylesheet. Building on that with Bootstrap 3, we rewrote the library once more to make it responsive by default with a mobile first approach.</p>
				-->
				<%=  render :partial => @template %>	

		</div>
	</div>

</div>

<script>
	$("h1").each(function(){
		create_proper_header(this,"h1")
	})
	
	var parent_id

	$("h2").each(function() {
		console.log($(this).html())
		add_item_in_nav("ul.nav.bs-sidenav", this, "")
		parent_id = $(this).html().replace(/\W+/g,"-")
		
		$(this).nextUntil("h2","h3").each(function(){
			console.log($(this).html())
			add_item_in_nav("ul.nav.bs-sidenav li:last ul", this, parent_id + "-")
			create_proper_header(this,"h3", parent_id + "-")
		})
		create_proper_header(this, "h2", "")
	})

	function create_proper_header(element,header_type, parent_id) {
		id = parent_id + $(element).html().replace(/\W+/g,"-")
		if (header_type == "h2" || header_type == "h1") 
			$(element).replaceWith('<div class="page-header"><' + header_type + ' id="' + id + '">' + $(element).html() + '</' + header_type + '></div>')
		else
			$(element).replaceWith('<' + header_type + ' id="' + id + '">' + $(element).html() + '</' + header_type + '>')
			
	}

	function add_item_in_nav(_parent,element, parent_id) {
		id = parent_id + $(element).html().replace(/\W+/g,"-")
		$(_parent).append('<li><a href="#' + id + '">' + $(element).html() + '</a><ul class="nav"></ul></li>')
	}

</script>

app/views/layouts/syndicate.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewCodelearn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
	
 	<meta name="description" content="<%= @description %>">
	<meta name="author" content="Codelearn.org">
	<meta name="keywords" content="<%= @keyword %>">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

	<!--Google Analytics Tracking Code begin-->
		<script type="text/javascript">

  		  var _gaq = _gaq || [];
  		  _gaq.push(['_setAccount', 'UA-32939456-1']);
 		  _gaq.push(['_setDomainName', 'codelearn.org']);
		  _gaq.push(['_trackPageview']);

  			(function() {
    		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
 		 	})();
		</script><!--Google Analytics Tracking Code End-->

</head>
<body style="padding:0">



		<!-- Header
	================================================== -->
	<header id="header">

		<!-- Navigation
		================================================== -->
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="/" style="padding-top:10px; padding-bottom:0px">
						<img src="http://www.codelearn.org/assets/cl_logo1.png" style="width:80px"/><b>Codelearn.org</b>
					</a>
					<div class="nav-collapse">
						<ul class="nav">
							<li class="active">
								<%= link_to android_tutorial_path, :class => "btn btn-default", :style => "margin-top:0; border:0", "data-toggle" => "dropdown" do %>
									Android Concept Lessons <span class="caret" style="display:inline-block"></span>
								<% end %>
								<ul class="dropdown-menu">
									<li><%= link_to "1. Android Introduction", android_concept_lesson_path("android-introduction") %></li> 	
									<li><%= link_to "2. Android Setup", android_concept_lesson_path("android-setup") %></li> 	
									<li><%= link_to "3. Android Hello World", android_concept_lesson_path("android-hello-world") %></li> 	
									<li><%= link_to "4. Android Layout", android_concept_lesson_path("android-layout") %></li> 	
									<li><%= link_to "5. Android Activity", android_concept_lesson_path("android-activity") %></li> 	
									<li><%= link_to "6. Android Intent", android_concept_lesson_path("android-intent") %></li> 	
									<li><%= link_to "7. Android Views", android_concept_lesson_path("android-views") %></li> 	
									<li><%= link_to "8. Android ListView", android_concept_lesson_path("android-listview") %></li> 	
									<li><%= link_to "9. Android Log", android_concept_lesson_path("android-log") %></li> 	
								</ul>
								</li>

							</ul>

						</div><!--/.nav-collapse -->
					</div><!-- end .container -->
				</div><!-- end .navbar-inner -->
			</div><!-- end .navbar -->
			</header>
			<div id="content">
				<%= yield %>
			</div>

		<!--	<footer>
			<div class="container">
				<div class="row">
					<div class="span4">
						<h3>Codelearn.org</h3>
						<ul>
							<li><a href="#" title="">Android Tutorial</a></li>
							<li><a href="#" title="">Lesson 1</a></li>
							<li><a href="#" title="">Lesson 2</a></li>
							<li><a href="#" title="">Lesson 3</a></li>
						</ul>
					</div>
					<div class="span4 social-networks">
						<h3>Stay in touch</h3>
						<p>Stay in touch on social networks</p>
						<a href="#" title="Follow us on Facebook" class="icon-facebook"></a>
						<a href="#" title="Follow us on Twitter" class="icon-twitter"></a>
						<a href="#" title="Follow us on Google Plus" class="icon-google-plus"></a>
						<a href="#" title="Follow us on Google Plus" class="icon-github"></a>
						<a href="#" title="Follow us on Google Plus" class="icon-pinterest"></a>
					</div>
					<div class="span4">
						<h3>Newsletter</h3>
						<p>Subscribe to our monthly newsletter and be the first to know about our news and special deals!</p>
						<form>
							<input type="text" placeholder="Enter your E-mail" />
							<input type="submit" class="btn" value="Ok" />
						</form>
					</div>
				</div> 
			</div> 

			<div id="footer-extra">
				<div class="container">
					<div class="row">
						<div class="span4">
							&copy; 2010—2012 Your company
						</div>
						<div class="span4">
							<i class="icon-phone"></i> &nbsp; 
							00123 320 000 123 456
						</div>
						<div class="span4">
							<i class="icon-envelope"></i> &nbsp; 
							hello@yourcomapny.com
						</div>
					</div> 
				</div> 
			</div>

			</footer> -->

			<script src="http://getbootstrap.com/docs-assets/js/holder.js"></script>
			<script src="http://getbootstrap.com/docs-assets/js/application.js"></script>



			<script>
				$("blockquote").each(function(){
					$(this).replaceWith('<div class="alert alert-warning">' + $(this).text() + "</div>")
				})

				$("code").each(function(){
					if ( $(this).parent().text() == $(this).text() && $(this).parent()[0].tagName == "P" ) {
						$(this).unwrap()
					}
				})
				$("#content img").each(function(){
					console.log("here")
					$(this).addClass("img-polaroid")
					$(this).parent().addClass("ac")
				})

				$(".vertical-align-me").each(function() {
					var margin_top = ($(this).parent().parent().height() - $(this).height() )/2
					$(this).css("margin-top", margin_top)
				})

			</script>

		</body>
	</html>